### ISSUE TITLE
Change the light intensity

### ISSUE THREAD

**Issue by GregorBiswanger** [porsager/busylight#18]
First of all, best **thanks** for the great work of you! 

How I can change the light intensity? For example, the green is very weak.

Cheers,
Gregor

**Comment by porsager** [comment]
Hi Grigor. Thanks ;)

I think there was a change in the latest busylight version that does RGB values a bit differently, but I haven't got one on hand to test it, but it's probably because the wrong values are sent even when doing something like `busylight.light('#00FF00')`.

Have you tried playing around with the degamma option?

**Comment by GregorBiswanger** [comment]
Cool! Thanks that helps... I will write TypeScript TypeDefinition files for you.. :)

**Comment by porsager** [comment]
Neat :) thanks!

**Comment by GregorBiswanger** [comment]
Pull Request with TypeScript support has been submitted. :)
